vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set relativenumber")
vim.keymap.set('t', '<C-w>h', "<C-\\><C-n><C-w>h",{silent = true})
vim.keymap.set('t', '<C-w>j', "<C-\\><C-n><C-w>j",{silent = true})
vim.keymap.set('t', '<C-w>k', "<C-\\><C-n><C-w>k",{silent = true})
vim.keymap.set('t', '<C-w>l', "<C-\\><C-n><C-w>l",{silent = true})
vim.g.mapleader = " "
